### ISSUE TITLE
Modify cell separation

### ISSUE THREAD

**Issue by lorenzovecchietti** [ansys/pyaedt-examples#121]
### 📝 Description of the feature

I think the spacing in the pyaedt-example should be changed. We should have equal spacing or more space on top than on bottom (as almost always the text is commenting the following code)
![immagine](https://github.com/ansys-internal/pyaedt-examples/assets/58366962/d248126a-c64c-47ae-8270-9c3becb8aa5c)

### 💡 Steps for implementing the feature

-

### 🔗 Useful links and references

-

**Comment by Devin-Crawford** [comment]
@SMoraisAnsys : I'm already working on this (#265). Please go ahead and assign it to me. I'll update the templates.

**Comment by SMoraisAnsys** [comment]
Thanks for handling that @Devin-Crawford, I gave it a try and forgot to push the changes. I can't find the changes locally :(
If I remember correctly, I had some nice result by changing CSS content in https://github.com/ansys/pyaedt-examples/tree/main/doc/source/_static/css

**Comment by Devin-Crawford** [comment]
This does the trick:
```python
# +
import os
import tempfile
import time

import ansys.aedt.core
# -
```
